### ISSUE TITLE
Tamaño de la foto

### ISSUE THREAD

**Issue by MarceloRodriguezSanti** [pdepmartestm/bienvenida-2023-FranBarroso2#1]
Si te interesa podes modificar el tamaño de la imagen con el siguiente código:

<img src="foto.jpeg" width=20%> (el 20 lo podes cambiar)

**Comment by MarceloRodriguezSanti** [comment]
Este código `<img src="foto.jpeg" width=20%>`, perdón esto es nuevo para mi

**Comment by FranBarroso2** [comment]
Perfecto ya lo cambio
